# ~/.config/starship.toml

[directory]
format = "\\[[$path]($style)[$read_only]($read_only_style)\\] "
truncation_length = 16
truncation_symbol = "../"

[hostname]
ssh_only = false
format = "@[$hostname](bold blue) "

[username]
format = "[$user]($style)"
show_always = true

[battery]
disabled = true

[character]
success_symbol = "[Î»](bold green)"
error_symbol = "[Î»](bold red)"
vicmd_symbol = "[V](bold green)"

[git_commit]
only_detached = false
tag_symbol = "ðŸ”– "
