return {
  {
    "RutaTang/quicknote.nvim",
    dependencies = { "nvim-lua/plenary.nvim" },
    keys = {
      { "<leader>nlc", "<cmd>:lua require('quicknote').NewNoteAtCurrentLine()<cr>", desc = "Create" },
      { "<leader>nlo", "<cmd>:lua require('quicknote').OpenNoteAtCurrentLine()<cr>", desc = "Open" },
      { "<leader>nld", "<cmd>:lua require('quicknote').DeleteNoteAtCurrentLine()<cr>", desc = "Delete" },
      { "<leader>ncc", "<cmd>:lua require('quicknote').NewNoteAtCWD()<cr>", desc = "Create" },
      { "<leader>nco", "<cmd>:lua require('quicknote').OpenNoteAtCWD()<cr>", desc = "Open" },
      { "<leader>ncd", "<cmd>:lua require('quicknote').DeleteNoteAtCWD()<cr>", desc = "Open" },
      { "<leader>ngc", "<cmd>:lua require('quicknote').NewNoteAtGlobal()<cr>", desc = "Create" },
      { "<leader>ngo", "<cmd>:lua require('quicknote').OpenNoteAtGlobal()<cr>", desc = "Open" },
      { "<leader>ngd", "<cmd>:lua require('quicknote').DeleteNoteAtGlobal()<cr>", desc = "Delete" },
      { "<leader>nLb", "<cmd>:lua require('quicknote').ListNotesForCurrentBuffer()<cr>", desc = "Current buffer" },
      { "<leader>nLc", "<cmd>:lua require('quicknote').ListNotesForCWD()<cr>", desc = "CWD" },
      { "<leader>nLg", "<cmd>:lua require('quicknote').ListNotesForGlobal()<cr>", desc = "Global" },
      { "<leader>nLf", "<cmd>:lua require('quicknote').ListNotesForAFileOrWDInCWD()<cr>", desc = "File or dir" },
      { "<leader>njp", "<cmd>:lua require('quicknote').JumpToPreviousNote()<cr>", desc = "Previous" },
      { "<leader>njn", "<cmd>:lua require('quicknote').JumpToNextNote()<cr>", desc = "Next" },
      { "<leader>nCb", "<cmd>:lua require('quicknote').GetNotesCountForCurrentBuffer()<cr>", desc = "Current buffer" },
      { "<leader>nCc", "<cmd>:lua require('quicknote').GetNotesCountForCWD()<cr>", desc = "CWD" },
      { "<leader>nCg", "<cmd>:lua require('quicknote').GetNotesCountForGlobal()<cr>", desc = "Global" },
      { "<leader>ns", "<cmd>:lua require('quicknote').ToggleNoteSigns()<cr>", desc = "Toggle signs" },
      { "<leader>nEb", "<cmd>:lua require('quicknote').ExportNotesForCurrentBuffer()<cr>", desc = "Current buffer" },
      { "<leader>nEc", "<cmd>:lua require('quicknote').ExportNotesForCWD()<cr>", desc = "CWD" },
      { "<leader>nEg", "<cmd>:lua require('quicknote').ExportNotesForGlobal()<cr>", desc = "Global" },
      { "<leader>nIb", "<cmd>:lua require('quicknote').ImportNotesForCurrentBuffer()<cr>", desc = "Current buffer" },
      { "<leader>nIc", "<cmd>:lua require('quicknote').ImportNotesForCWD()<cr>", desc = "CWD" },
      { "<leader>nIg", "<cmd>:lua require('quicknote').ImportNotesForGlobal()<cr>", desc = "Global" },
    },
  },
}
